### ISSUE TITLE
Association Field visualization and explanation

### ISSUE THREAD

**Issue by mrronchi** [openpifpaf/openpifpaf#348]
Hi @svenkreiss, congrats for the great work and code repo. 

I am using the flags `--debug-images --debug-indices cif:5 caf:5` to visualize the part association fields for a random body part:

| Confidence field component | Vector field component |
| ----------- | ----------- |
| ![Screenshot_20210216_161225](https://user-images.githubusercontent.com/22902802/108137946-ce519300-7071-11eb-9edb-5abea18fc36f.png)  |   ![Screenshot_20210216_153046](https://user-images.githubusercontent.com/22902802/108136107-3c945680-706e-11eb-83d3-bd2434209268.png)       |

If I understand correctly the paper and code, you are showing the confidence field over the entire image and the vector field only for the pixels in which the confidence is larger than 0.5. 

It would be great if you could please help me clarify a few questions (and possibly point me to the part of the code that explains the answer?):

1. Is the confidence field in the image above set to `a_c = 1` for all the pixels in that blue box and zero for every pixel outside? If not, how is it set?
2. How is that area in which the confidence is `a_c = 1` (or the value from your answer to my previous question) determined?
3. The vector field should be shown for all pixels having confidence larger than 0.5, however in the visualization above it seems like not all the pixels in the blue box are visualized. Is this for the purpose of a better visualization or am I missing something?
4. The visualizations show the paf confidence (plot in the left), and the two paf vectors (x1, y1, x2, y2) pointing from a certain pixel to the two associated parts (plot in the right). However, there is no visualization for the width components. Could you please explain what they represent and how to visualize their meaning?

Thank you so much for any help you can offer!

**Comment by svenkreiss** [comment]
Thanks for you interest in OpenPifPaf.

1. Yes. There should be a number scale next to the color bar, but with some aspect ratios that gets cut.
2. See encoder/caf.py
3. The vector field is over the feature map which has a stride of 8 pixels.
4. The square box represents the joint scale. The b from the Laplace loss has no supervision and is therefore not in the ground truth.

I hope that helps.

**Comment by mrronchi** [comment]
Thanks for your prompt reply. Following-up to your answers:

2) Would it be possible to explain the idea very briefly in words? I can't seem to find it in the paper and that is making it hard to reverse-engineer the code.

4) So that means that the components a^ij_b1 and a^ij_b2 are not used unless one trains with the Laplacian loss (i.e. PAF could be 5-dimensional), correct? Also, I might be missing something trivial, but since the loss in eq.2 has only one b term, how are a^ij_b1 and a^ij_b2 used?

Thanks a lot again, I truly appreciate your help.

**Comment by mrronchi** [comment]
@svenkreiss  - Just wondering if you had a chance to look at my follow-up questions. Thanks again for your help on this.

**Comment by svenkreiss** [comment]
Hello @mrronchi , we have published a new paper that might give you some extra details:
https://arxiv.org/abs/2103.02440
It also specifies the current nomenclature of the CIF and CAF fields that has evolved slightly from the original paper.
