### ISSUE TITLE
Train a different number of keypoints in the format of the coco data set

### ISSUE THREAD

**Issue by ChalsonLee** [openpifpaf/openpifpaf#372]
After I annotated my own data set in the coco data set format, I want to predict 8 key points. Where do I need to modify the code?
I encountered the following error：
`RuntimeError: The size of tensor a (17) must match the size of tensor b (8) at non-singleton dimension `1``

thanks for your time.

**Comment by svenkreiss** [comment]
You'll need to create a new plugin. Check out the CrowdPose plugin and replicate what you need for your use case: https://vita-epfl.github.io/openpifpaf/plugins_crowdpose.html

**Comment by svenkreiss** [comment]
Hello @ChalsonLee , there is a new tutorial by @bertoni9  that is available here:
https://openpifpaf.github.io/dev/plugins_custom.html
It gives quite a bit more information about how to start your own plugin that also is in COCO format.
