### ISSUE TITLE
About force complete pose

### ISSUE THREAD

**Issue by NgTuong** [openpifpaf/openpifpaf#391]
Hi @svenkreiss,
with force complete pose, decoder time increases approximately linear when number of people too increase!!!
Without force complete pose , How to draw full keypoints for person from fields?

**Comment by svenkreiss** [comment]
Do you want to force a complete pose without using `--force-complete-pose`?

**Comment by NgTuong** [comment]
@svenkreiss,
Yes, I want to visualize full keypoints output without `--force-complete-pose` !!!

**Comment by svenkreiss** [comment]
That's what `--force-complete-pose` is for. We don't have another way to do that.

**Comment by NgTuong** [comment]
thank @svenkreiss
