### ISSUE TITLE
Eval and visualization with ground truth from custom dataset

### ISSUE THREAD

**Issue by taylormordan** [openpifpaf/openpifpaf#397]
Hello @svenkreiss,

When evaluating on a custom dataset that returns ground truth annotations directly, these are converted back to the original images (removing any pre-processing) only for visualization purpose, but not before accumulating results for the metrics.
However, they would need to be the same annotations for both steps.

https://github.com/openpifpaf/openpifpaf/blob/31da82cbe5d72939726d5797e67691540fa0c151/openpifpaf/eval.py#L161-L168

It is still possible to work around it from the dataloader (have the `inverse_transform` there and preventing it happening a second time for visualization), but it seems unnatural and not the intended way.
Shouldn't the call to `inverse_transform` be done at the same time for both predictions and ground truths in the case of a custom dataset?

I know ground truths are read with pycocotools for evaluation on MS COCO, so this works fine in this case.
Is it expected to have this kind of pipeline for any other dataset too?

Thank you for your help.

**Comment by svenkreiss** [comment]
Hi @taylormordan , I agree with that analysis. So moving line 168 to line 163 would fix it, right?
That looks good to me. Do you want to make a one-line PR? I can also put that in. Let me know.

**Comment by svenkreiss** [comment]
We should also get the opinion of @bertoni9 on this. The ApolloCar3D metric would change. Lorenzo, can you confirm that this would be the right fix or did you do something else in that metric that would brake with the suggested fix?

**Comment by svenkreiss** [comment]
Actually, ApolloCar3D probably wouldn't change as the ground truth is rescaled instance by instance.

**Comment by taylormordan** [comment]
> Hi @taylormordan , I agree with that analysis. So moving line 168 to line 163 would fix it, right?
> That looks good to me. Do you want to make a one-line PR? I can also put that in. Let me know.

Yes that should fix it.
I can do a PR, I may just wait for confirmation by @bertoni9 that it is ok for the new dataset too.

**Comment by bertoni9** [comment]
Thanks for reaching out. Yes, inside the metric the ground-truth is rescaled to simulate CPM crop size of 368 pixels, so the PR should not affect it.

**Comment by bertoni9** [comment]
However, when I change that line and run it, I have an assertion error (below). 
Also, ApolloCar3D metric uses annotation.fixed_bbox to rescale instances.

  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lorenzo/openpifpaf/openpifpaf/eval.py", line 258, in <module>
    main()
  File "/home/lorenzo/openpifpaf/openpifpaf/eval.py", line 254, in main
    evaluate(args)
  File "/home/lorenzo/openpifpaf/openpifpaf/eval.py", line 163, in evaluate
    gt_anns = [ann.inverse_transform(image_meta) for ann in gt_anns]
  File "/home/lorenzo/openpifpaf/openpifpaf/eval.py", line 163, in <listcomp>
    gt_anns = [ann.inverse_transform(image_meta) for ann in gt_anns]
  File "/home/lorenzo/openpifpaf/openpifpaf/annotation.py", line 173, in inverse_transform
    assert self.fixed_bbox is None
AssertionError

**Comment by taylormordan** [comment]
I guess you would have the same issue if you try to visualize images with `--show-final-image` in the current version.
That assert would prevent any ground truth annotation to be inverted if obtained by the transform `ToKpAnnotations`, since it sets this field, right?
If that is the case, I think it is worth fixing it anyway.

I am not sure I understand what the `fixed_` part means in the field `annotation.fixed_bbox`.
From what I understand, it comes from the `bbox` of ground truth annotations, and so would be modified accordingly to the data augmentation.
So I would think it should be inverted back to the original image to still correspond with the inverted ground truth keypoints and predictions.
If it really needs to stay unmodified, can't we just remove that assert line?

**Comment by svenkreiss** [comment]
The assert is there because the inversion is not implemented.

Normally, bounding boxes from keypoints are dynamic depending on where the keypoints are and that also changes dynamically depending on NMS of keypoints. Therefore, `bbox` is normally computed based on keypoints. However, for detections or for ground truth, there can be a "fixed" bounding box that is provided independently from the keypoint data.

**Comment by taylormordan** [comment]
Thanks, I see, it makes much more sense now!

I have opened PR #399 for both issues, please let me if anything is missing.

**Comment by svenkreiss** [comment]
PR looks great @taylormordan . Thanks for finding this issue and fixing it!
