### ISSUE TITLE
Checkpoint for MobileNetV2 not working from torchvision 0.9

### ISSUE THREAD

**Issue by taylormordan** [openpifpaf/openpifpaf#405]
Hello @svenkreiss,

It seems that the checkpoint for `mobilenetv2` is not working with the latest version of torchvision.
When trying to load it, I get the following error:
```
AttributeError: Can't get attribute 'ConvBNReLU' on <module 'torchvision.models.mobilenet' from '/home/mordan/venvs/plugin/lib/python3.7/site-packages/torchvision/models/mobilenet.py'>
```
This can be reproduced with any command loading the checkpoint, e.g.:
```
python3 -m openpifpaf.benchmark --checkpoint mobilenetv2
```

I think this is linked to [this change](https://github.com/pytorch/vision/pull/3177) in torchvision, which was added in version 0.9.0.
I have the issue with torchvision 0.9.1 (pytorch 1.8.1), but haven't tried with previous versions.

It should be possible to copy the weights of the existing checkpoint into a new MobileNetV2 instance, which should have the right updated paths to the modules that have been moved.
I should be able to give you such a checkpoint if you are interested.
But it will likely not work with previous torchvision versions.

**Comment by taylormordan** [comment]
I just saw in #388 that you already know this issue.
Let me know if you are interested to try to fix this with newer versions of torchvision.

**Comment by svenkreiss** [comment]
Thanks @taylormordan . I am testing a fix now.

**Comment by agrija9** [comment]
Were you able to fix this issue with recent openpifpaf, torch and torchvision versions?

**Comment by JJLimmm** [comment]
Still facing this issue as well when trying to use Mobilenetv2 checkpoint to run video inference. Current torchvision version is 0.14.0
