### ISSUE TITLE
Animal-Pose Dataset

### ISSUE THREAD

**Issue by itsyoavshalev** [openpifpaf/openpifpaf#410]
Is there a pre trained model for the Animal-Pose Dataset?

**Comment by svenkreiss** [comment]
This is a high priority for us. We will release something on animals very soon. CC @bertoni9

**Comment by bertoni9** [comment]
Hi @itsyoavshalev, 

We have just released the pre-trained model for the animalpose dataset and the guide for it.

Hope it helps,
Lorenzo

**Comment by svenkreiss** [comment]
Until the next OpenPifPaf release, this is only in the DEV version of the Guide:
https://openpifpaf.github.io/dev/plugins_animalpose.html

**Comment by itsyoavshalev** [comment]
openpifpaf.network.Factory(checkpoint='shufflenetv2k30-animalpose').factory() yields the following error:
[Errno 2] No such file or directory: 'shufflenetv2k30-animalpose'

**Comment by svenkreiss** [comment]
This is now in release v0.12.10:
https://openpifpaf.github.io/plugins_animalpose.html#predict
