### ISSUE TITLE
Model input size warning when doing export to ONNX

### ISSUE THREAD

**Issue by vladimirmujagic** [openpifpaf/openpifpaf#434]
Hi,

I was wondering about model input size `(H, W)` when doing export to ONNX format, default size is set to `(129, 97)` and i notice input size warning in export script.  For my specific usecase I would like to generate models with input size `(160, 160); (320, 320); (640, 640)` but according to warning code it should be `(161, 161); (321, 321); (641, 641)` if I am not mistaken.  

Is this possible and what is the reason of forcing that 1 pixel?

**Comment by svenkreiss** [comment]
The argument for the evaluation size also applies here:
https://openpifpaf.github.io/faq.html#why-evaluate-with-641px-instead-of-640px 

It's not really an issue if you cannot have that extra pixel. It's only a warning.

**Comment by vladimirmujagic** [comment]
Great thank you for fast reply!
