### ISSUE TITLE
Onnx dynamic export input

### ISSUE THREAD

**Issue by adujardin** [openpifpaf/openpifpaf#436]
By default the name of the dynamic axes doesn't match the name of the input tensor, resulting in a constant batch value.

There's a warning displayed about this and the issue can be seen with netron

```
warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
```

The fix is pretty simple, "input" should be renamed to "input_batch" (to match `input_names`) here https://github.com/openpifpaf/openpifpaf/blob/7000b4750b3927511bea5acb2cf2314fc934df84/openpifpaf/export_onnx.py#L66

With the current code: 
![Before fix](https://user-images.githubusercontent.com/12609780/120995803-0f3af800-c786-11eb-8507-e2536efe0bfc.png)

After the fix:
![After fix](https://user-images.githubusercontent.com/12609780/120995813-119d5200-c786-11eb-83ca-710fe0fd1ec3.png)

**Comment by svenkreiss** [comment]
Thanks for the detailed report @adujardin .
I'll look into it.

**Comment by adujardin** [comment]
When running the correct onnx model with TensorRT and a batch > 1 it crashes (batch == 1 is working as expected).

I'm not sure what's happening exactly but it seems the head forward path has a hypothesis about the batch size. I didn't dive into the code but I guess [this is the part in question](https://github.com/openpifpaf/openpifpaf/blob/7000b4750b3927511bea5acb2cf2314fc934df84/openpifpaf/network/heads.py#L170)

When running the model with TensorRT (reproducible with `trtexec` tool, with `trtexec --onnx=openpifpaf-resnet50_dynx3x352x608.onnx --explicitBatch --minShapes=input_batch:2x3x352x608 --optShapes=input_batch:4x3x352x608 --maxShapes=input_batch:8x3x352x608`), it always fails with an exception and segfault. Using a previous version to export the model a while back, the issue was obvious with netron when looking at the head layers dimensions.

![old_model_netron](https://user-images.githubusercontent.com/12609780/121016995-13264480-c79d-11eb-8b4d-56db4319cdcf.png)

I tried this branch, the problem persists (netron doesn't show the full dimension on this one, not sure why). Around the Add_201 shouldn't the dimension depend on the batch size?

![new_model_netron](https://user-images.githubusercontent.com/12609780/121017026-1a4d5280-c79d-11eb-855e-4caf8cc82af8.png)

The runtime test is failing https://github.com/openpifpaf/openpifpaf/pull/437/checks?check_run_id=2763216388 (on the PR linked to this issue) and this could be linked.

**Comment by adujardin** [comment]
Ok I remembered I used the ["infer shape"](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#running-shape-inference-on-an-onnx-model) from onnx to check the dimension, that's why it was displayed. The issue is indeed present in the recent model.

This is the script I used :

```python
import onnx
from onnx import shape_inference

original_model = onnx.load("openpifpaf-resnet50_dynx3x352x608.onnx")

# Check the model and print Y's shape information
onnx.checker.check_model(original_model)
print('Before shape inference, the shape info of Y is:\n{}'.format(original_model.graph.value_info))

# Apply shape inference on the model
inferred_model = shape_inference.infer_shapes(original_model)

# Check the model and print Y's shape information
onnx.checker.check_model(inferred_model)
print('After shape inference, the shape info of Y is:\n{}'.format(inferred_model.graph.value_info))

onnx.save_model(inferred_model,"openpifpaf-resnet50_dynx3x352x608_inferred.onnx")
```

This is the result:

![netron_r50_dyn](https://user-images.githubusercontent.com/12609780/121021091-4cf94a00-c7a1-11eb-82b8-5801e530babe.png)

**Comment by svenkreiss** [comment]
The new branch now seems to pass the test. This is without shape_inference.
However, this only seems to work in PyTorch>=1.8, so I have deactivated the test case for batch_dim=2 for PyTorch 1.7.
Can you check whether this branch now gives you a workable model?

**Comment by adujardin** [comment]
It's now working as expected :+1: 
TensorRT is able to run it, and the shape inference is correct 

![shape_infer](https://user-images.githubusercontent.com/12609780/121044348-c69b3300-c7b5-11eb-9edc-36fa731367e7.png)

It was indeed the 'int' cast that forced the constant in `batch_size = int(x_size[0])` that was causing the issue.

**Comment by svenkreiss** [comment]
Great, thanks!

**Comment by RTae** [comment]
@adujardin Hi, do you have example to run onnx with tensorrt ?
