### ISSUE TITLE
Need help on running benchmark

### ISSUE THREAD

**Issue by seungwonpark** [openpifpaf/openpifpaf#445]
Hi, thanks for developing openpifpaf.

As shown in [intro.html#pre-trained-models](https://openpifpaf.github.io/intro.html#pre-trained-models), we should be able to reproduce the table by running
```bash
python -m openpifpaf.benchmark --checkpoints resnet50 shufflenetv2k16 shufflenetv2k30
```
But this doesn't work directly.
1. I needed to first install `thop` and `pycocotools` manually.
2. It gives FileNotFoundError. Looks like I need to download coco dataset somewhere and specify its path as an argument. The error log is shown in https://pastebin.com/KjpcYNxr

Is there any related docs elsewhere?

**Comment by svenkreiss** [comment]
Hello @seungwonpark , that could indeed be better documented. It is somewhere but not very well linked together. 

We have some optional dependencies. All are listed here:
https://openpifpaf.github.io/dev.html#missing-dependencies
Try at least `test` which should install `thop` and `pycocotools`.

And yes, you need the dataset for the benchmark: https://openpifpaf.github.io/datasets.html#download-coco-data

**Comment by seungwonpark** [comment]
Thanks for the links! `pip install openpifpaf[test]` works well.

But how should I specify the path to the (downloaded) datasets to `openpifpaf.benchmark`? I could not find relevant description at https://openpifpaf.github.io/cli_help.html#benchmark

**Comment by svenkreiss** [comment]
Datasets are expected to be in your current directory. I.e. your current directory must contain the folder `data-mscoco`. It can be a symbolic link.

**Comment by seungwonpark** [comment]
Works like a charm. Thanks a lot!
![image](https://user-images.githubusercontent.com/13394294/122892370-4c0b0f80-d380-11eb-99ef-cc7995134af7.png)
