### ISSUE TITLE
Zero Values keypoints when confidence equals zeros

### ISSUE THREAD

**Issue by SirNader** [openpifpaf/openpifpaf#447]
Hello, 
Recently, I've been working on 3D pose reconstruction model from 2D pose keypoints to find out which 2D Pose model works best with my model.
I've noticed that some keypoint values were equal to zero when the confidence is zero (usually when there's some occlusion)
My question is "Is the model trained to output zero values when a body part is occluded/(hard to predict)? or Is it just a decoder thing?"
If the decoder sets values to zeros, Which part of the decoder code can I modify to disable this?

In the screenshot below, I have plotted keypoints using OpenCV.
![image](https://user-images.githubusercontent.com/37120481/123560608-95ee5e00-d7a3-11eb-97c8-fe4186afdcd5.png)

Thanks in advance

**Comment by svenkreiss** [comment]
This is a bottom-up method. There is nothing in the decoder that sets the confidences to zero after they have been found. They were never found in the first place. You can enable an extra step that tries harder to produce complete poses: `--force-complete-pose`.

**Comment by SirNader** [comment]
> This is a bottom-up method. There is nothing in the decoder that sets the confidences to zero after they have been found. They were never found in the first place. You can enable an extra step that tries harder to produce complete poses: `--force-complete-pose`.

Thanks for clarifying!
