### ISSUE TITLE
instance-threshold and force-complete-pose

### ISSUE THREAD

**Issue by bertoni9** [openpifpaf/openpifpaf#450]
Hi @svenkreiss, 

It seems I cannot change the instance-threshold anymore when having force-complete-pose active. I saw this is also being mentioned in the help: 
```
group.add_argument('--instance-threshold', type=float, default=None,
                       help=('filter instances by score (0.0 with --force-complete-pose '
                             'else {})'.format(utils.nms.Keypoints.instance_threshold)))
```
What is the reason for this? Alternatively, which threshold do you suggest to use to filter instances?

Many thanks,
Lorenzo

**Comment by svenkreiss** [comment]
Hi @bertoni9 , what is written in the parentheses is for the default value. If you cannot change the instance threshold with this flag then this is a bug.

**Comment by svenkreiss** [comment]
It's working for me.

**Comment by bertoni9** [comment]
Ok thanks! I was using the threshold to increase the number of instances, while with the current default this is already maximised.
