### ISSUE TITLE
annotation painter not working using openCV 

### ISSUE THREAD

**Issue by Ihebdhouibi** [openpifpaf/openpifpaf#456]
Here is my code : 

    cap = cv2.VideoCapture("fall 2.mp4")
    predictor = openpifpaf.Predictor(checkpoint='shufflenetv2k30')
    annotation_painter = openpifpaf.show.AnnotationPainter()

    while True:

        try:
            index, frame = cap.read()
            RGB_img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            predictions, gt_anns, image_meta = predictor.numpy_image(RGB_img)

            try:
                annotation_painter.annotations(RGB_img, predictions)
            except BaseException:
                print("Annotation painter not working ")

           cv2.imshow('frame', RGB_img)
           cv2.waitKey(1)

It throws an exception " Annotation painter not working", Same is happening if I set json_data to True (which I need)

**Comment by svenkreiss** [comment]
Correct. The painter is for a matplotlib canvas.
