### ISSUE TITLE
Why CenterPadTight has to pad 1 pixel?

### ISSUE THREAD

**Issue by twmht** [openpifpaf/openpifpaf#460]
Hi,

I found out that you use `CenterPadTight` (https://github.com/openpifpaf/openpifpaf/blob/main/openpifpaf/transforms/pad.py#L63) as a default preprocess in predcitor.

From the implementation, there are always 1 padding pixel around the image if the size of image is exactly the multiple of the given value.

for example, given 640x960, we would got 641x961.

is there any reason why you always pad 1 pixel around the image?

**Comment by svenkreiss** [comment]
Yes: https://openpifpaf.github.io/faq.html#why-evaluate-with-641px-instead-of-640px
