### ISSUE TITLE
Why shufflenetv2k30 don't need the pretrained weight?

### ISSUE THREAD

**Issue by twmht** [openpifpaf/openpifpaf#470]
Hi,

A pretrained weight is always needed if you want to train coco dataset.

But I found out that you don't have the pretrained weight with shufflenetv2k30 and you also got a good accuracy.

Have you ever trained from the pretrained weight from  shufflenetv2k30?

Why shufflenetv2k30 don't need the pretrained weight?

**Comment by svenkreiss** [comment]
The shufflenetv2k30 is something I made up for OpenPifPaf from smaller existing shufflenets. I am not aware of anyone who trained the k30 on ImageNet and certainly I haven't done so. So we simply don't have pretrained weights for this model. I dont know whether the performance would be better if we had them.

**Comment by twmht** [comment]
@svenkreiss 

Can you share how you design shufflenetv2k30? any rule?
