### ISSUE TITLE
Model tracing with force-complete-pose

### ISSUE THREAD

**Issue by bertoni9** [openpifpaf/openpifpaf#489]
Hi @svenkreiss, 

Thanks for all the work on tracing openpifpaf! 
We are able to save and load the traced model using the dev code in [export_torchscript.py](https://github.com/openpifpaf/openpifpaf/blob/dev/openpifpaf/export_torchscript.py), but somehow we cannot activate the `--force-complete-pose` command. We noticed that it wasn’t available in the `export_torchscript.py` file so we’ve tried to add it by calling the decoder `cli` and `configure` with:

```
@@ -77,12 +84,14 @@ def main():
                         version='OpenPifPaf {version}'.format(version=openpifpaf.__version__))

     openpifpaf.network.Factory.cli(parser)
+    openpifpaf.decoder.cli(parser)

     parser.add_argument('--outfile', default='openpifpaf-shufflenetv2k16.torchscript.pt')
     parser.add_argument('--input-width', type=int, default=129)
     parser.add_argument('--input-height', type=int, default=97)
     args = parser.parse_args()

+    openpifpaf.decoder.configure(args)
     openpifpaf.network.Factory.configure(args)

     model, _ = openpifpaf.network.Factory().factory()
```

The command we run to trace the model is: 
`python -m openpifpaf.export_torchscript --input-width 1921 --input-height 1201 --force-complete-pose`

It looks like the decoder is picking up our command line argument, but when we test the loaded traced model, the majority of keypoints have still zero values.

In addition, we have also tried to:
Set `force-complete-pose=True` as default [here](https://github.com/openpifpaf/openpifpaf/blob/dev/openpifpaf/decoder/cifcaf.py#L135)
Set `force-complete-pose=True` as default in the C++ decoder file [here](https://github.com/openpifpaf/openpifpaf/blob/dev/openpifpaf/csrc/src/module.cpp#L28)

Once we load the traced model, to test it on an image: we run the following steps:
```
model = torch.jit.load(‘...’)
img = Image.open(‘....’)
mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
std =  torch.tensor([0.2290, 0.2240, 0.2250]).view(3, 1, 1)
in_ = (torch.tensor(np.array(img).transpose(2, 0, 1))/255 - mean)/ std
# Make the image 1921x1201
in_ = torch.nn.functional.pad(in_, (0, 1, 0, 1))
with torch.no_grad():
  y = model(in_)
```

Is there any specific issue with tracing and force-complete-pose or we are missing something?

Additionally, we’ve been having difficulty tracing the model to run on the GPU. If we trace and then try to move the loaded model to the GPU afterwards we get some complaints about having cpu and cuda tensors. Similarly if we try to move the model to the GPU in the `export_torchscript.py` file. Were you able to get this tracing nicely on the GPU? I feel like we’re missing something obvious here.

Many thanks for your help.

**Comment by svenkreiss** [comment]
Thanks for that careful analysis. You are going deeper into TorchScript than any other user of OpenPifPaf I expect.

It is my understanding that setting the force_complete_pose flag of the C++ decoder before running the prediction should have worked. The flag is not serialized when tracing (so the traced models should be identical). But you need to set the flag before running prediction. You can do that from Python with:
`torch.classes.openpifpaf_decoder.CifCaf.set_force_complete(True)` 
Can you try that?

Fyi: the serialization is a bit documented here: https://pytorch.org/tutorials/advanced/torch_script_custom_classes.html

**Comment by svenkreiss** [comment]
@bertoni9 There was also a bug that is fixed with #495

**Comment by bertoni9** [comment]
Many thanks for your help @svenkreiss, it now works!

We are able to load the traced model and run inference on it. Just a quick question: the raw output is 4 columns instead of the usual 3. What do they represent? How can we convert them to a list of annotations?

Thanks again.

**Comment by svenkreiss** [comment]
Glad to hear it works :)

That format is close to what OpenPifPaf uses internally: confidence, x, y, joint scale

The cpp code is also used as "backend" in the Python decoder which also contains a few lines that convert from the cpp output to `Annotation` objects here: https://github.com/openpifpaf/openpifpaf/blob/14b41b6834dfde9cfc9acaee8ce017a161408120/openpifpaf/decoder/cifcaf.py#L267

**Comment by bertoni9** [comment]
Fantastic, thank you very much!
