### ISSUE TITLE
Batch prediction on images

### ISSUE THREAD

**Issue by grayskripko** [openpifpaf/openpifpaf#504]
Surprisingly, I couldn't find `openpifpaf.predictor` documentation with the full description of arguments and outputs anywhere.

I see `predictor.numpy_images` https://github.com/openpifpaf/openpifpaf/blob/main/openpifpaf/predictor.py#L161.
Will it help?
Also, I found https://github.com/openpifpaf/openpifpaf/blob/main/openpifpaf/predictor.py#L13 `batch_size`.
May it solve the problem?

The final thing I'm looking for is something close to your option in the documentation 
```
predictor = openpifpaf.Predictor(checkpoint='shufflenetv2k16')
predictions, gt_anns, image_meta = predictor.pil_image(pil_im)
```
but receive a numpy with one more dimension (n_images, height, width, n_colors) for a faster batch prediction.

Thank you for your great work, guys

**Comment by svenkreiss** [comment]
There is now some very basic documentation for the Predictor class here: https://openpifpaf.github.io/dev/moduledocs.html
So there is a plural version of the function you are using. Batch size might help you with the GPU part but the CPU part of the prediction will still run sequentially.

**Comment by grayskripko** [comment]
I'm not sure it works correctly.

Docs:
![image](https://user-images.githubusercontent.com/10427026/145820167-6ca0aefa-f93c-44d9-b3dd-dbbfbf209f53.png)

My code
![image](https://user-images.githubusercontent.com/10427026/145820006-e66deb1e-8c93-4ac5-b414-bdfdcec4f84b.png)

Output
![image](https://user-images.githubusercontent.com/10427026/145820041-cc6ca4ac-e24a-473b-8175-1159b2d36512.png)

**Comment by svenkreiss** [comment]
`batch_size` is a class variable. You need to remove it from the constructor and set it before with `openpifpaf.Predictor.batch_size = 8`.
