### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by sulei1998** [openpifpaf/openpifpaf#510]
When i use the package, i meet the error like this:
```sh
OSError: /root/miniconda3/envs/key_com/lib/python3.8/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
```

**Comment by svenkreiss** [comment]
Did you recently update pytorch? You might have to recompile the C++ part of OpenPifPaf. Easiest way to force that is to uninstall and reinstall OpenPifPaf.

**Comment by sulei1998** [comment]
I try to reinstall OpenPifPaf, but I meet the same error.

**Comment by svenkreiss** [comment]
Hmm, strange. How do you install OpenPifPaf? Can you provide some additional information: which Python version, which torch version, which operating system

**Comment by sulei1998** [comment]
I just use the commond 'pip install openpenpifpaf'.
I use it in ubuntu18.04, my python version is `3.8.0`. And I downgraded torch to 1.9.0.
Here is my package info:
![image](https://user-images.githubusercontent.com/56378342/142790474-79472f12-3489-4abc-9c59-27cc4acc6ac7.png)

**Comment by Julietty** [comment]
I have the same error, installed OpenPifPaf in miniconda on mac Catalina ```OSError: dlopen(/Users/jul/opt/miniconda3/lib/python3.8/site-packages/openpifpaf/_cpp.so, 6): Symbol not found: __ZN2at4_ops10max_pool2d4callERKNS_6TensorEN3c108ArrayRefIxEES7_S7_S7_b
  Referenced from: /Users/jul/opt/miniconda3/lib/python3.8/site-packages/openpifpaf/_cpp.so
  Expected in: /Users/jul/opt/miniconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib
 in /Users/jul/opt/miniconda3/lib/python3.8/site-packages/openpifpaf/_cpp.so```

Python 3.8.3, torch 1.9.0

**Comment by svenkreiss** [comment]
There is actually a test case that runs against almost the same configuration here:
https://github.com/openpifpaf/openpifpaf/runs/4291948321?check_suite_focus=true
Miniconda, Python 3.8.5, torch 1.9.0

**Comment by svenkreiss** [comment]
And just to double check: after you installed with `pip install openpifpaf` make sure there is no folder in the current directory that is called `openpifpaf`. Otherwise Python import gets confused.

**Comment by sulei1998** [comment]
I checked and made sure there was no file named `openpifpaf` in the current folder. I even change to another folder to import the package but found the same error.
![image](https://user-images.githubusercontent.com/56378342/142961658-7d68510c-3328-43ce-8c1a-dff47e26dca2.png)

**Comment by hstm** [comment]
Same error here (MacOS 12.0.1)

Symbol not found: __ZN2at4_ops10max_pool2d4callERKNS_6TensorEN3c108ArrayRefIxEES7_S7_S7_b
  Referenced from: /opt/miniconda3/envs/opp2/lib/python3.8/site-packages/openpifpaf/_cpp.so
  Expected in: /opt/miniconda3/envs/opp2/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib

Workaround: Don't install the openpifpaf package from PyPI, check out and install it yourself instead.
Steps:
```
pip install torch==1.9.0 torchvision==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html
git clone https://github.com/openpifpaf/openpifpaf.git
cd openpifpaf
pip install -e . --no-build-isolation
```

**Comment by svenkreiss** [comment]
I couldn't reproduce any of this locally, but now I am able to reproduce some errors in CI. I am attempting fixes here: https://github.com/openpifpaf/openpifpaf/pull/518

My understanding is that this is due to how torch loads dynamic libraries and how that interferes with build isolation in recent versions of pip. What seems to work for now is `pip install --no-build-isolation openpifpaf`. 

There seems to be an additional issue with similar symptoms with torch 1.10 on MacOS builds. MacOS builds with torch 1.9 seem fine when `--no-build-isolation` is used.

**Comment by sulei1998** [comment]
Thanks for your help! It seems to works! Have a good day!
