### ISSUE TITLE
issue with torch-vision

### ISSUE THREAD

**Issue by rmhiri-gpsw** [openpifpaf/openpifpaf#517]
after installing openpifpaf, (openpifpaf-0.13.0) and when I tried to test it using `python3 -m openpifpaf.predict --help` I got an error with torch vision, here is my output (torchvision version is torchvision-0.11.1): 

> libc++abi: terminating with uncaught exception of type c10::Error: Type c10::tagged_capsule<openpifpaf::decoder::CifCaf> could not be converted to any of the known types. Exception raised from operator() at /private/var/folders/ns/6kcfqjw14tj8csv_1y018rh80000gn/T/pip-build-env-gfgjhrl6/overlay/lib/python3.9/site-packages/torch/include/ATen/core/jit_type.h:1674 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 98 (0x109e89522 in libc10.dylib)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 106 (0x109e87c3a in libc10.dylib)
frame #2: c10::detail::getTypePtr_<c10::tagged_capsule<openpifpaf::decoder::CifCaf> >::call()::'lambda'()::operator()() const + 264 (0x134d6ad68 in _cpp.so)
frame #3: c10::detail::getTypePtr_<c10::tagged_capsule<openpifpaf::decoder::CifCaf> >::call() + 27 (0x134d6ab9b in _cpp.so)
frame #4: c10::detail::infer_schema::(anonymous namespace)::createArgumentVector(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) + 206 (0x114d40ede in libtorch_cpu.dylib)
frame #5: c10::detail::infer_schema::make_function_schema(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) + 123 (0x114d40c8b in libtorch_cpu.dylib)
frame #6: torch::jit::Function* torch::class_<openpifpaf::decoder::CifCaf>::defineMethod<torch::class_<openpifpaf::decoder::CifCaf>& torch::class_<openpifpaf::decoder::CifCaf>::def<long long, at::Tensor const&>(torch::detail::types<void, long long, at::Tensor const&>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::initializer_list<torch::arg>)::'lambda'(c10::tagged_capsule<openpifpaf::decoder::CifCaf>, long long, at::Tensor const&)>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::initializer_list<torch::arg>) + 450 (0x134d6a112 in _cpp.so)
frame #7: torch::class_<openpifpaf::decoder::CifCaf>& torch::class_<openpifpaf::decoder::CifCaf>::def<long long, at::Tensor const&>(torch::detail::types<void, long long, at::Tensor const&>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::initializer_list<torch::arg>) + 82 (0x134d5c002 in _cpp.so)
frame #8: TORCH_LIBRARY_init_openpifpaf_decoder(torch::Library&) + 21995 (0x134d432cb in _cpp.so)
frame #9: torch::detail::TorchLibraryInit::TorchLibraryInit(torch::Library::Kind, void (*)(torch::Library&), char const*, c10::optional<c10::DispatchKey>, char const*, unsigned int) + 204 (0x134d5b09c in _cpp.so)
frame #10: _GLOBAL__sub_I_module.cpp + 138 (0x134d92faa in _cpp.so)
frame #11: 0x0 + 4641871559 (0x114ad56c7 in ???)
frame #12: 0x0 + 4641872594 (0x114ad5ad2 in ???)
frame #13: 0x0 + 4641850550 (0x114ad04b6 in ???)
frame #14: 0x0 + 4641841775 (0x114ace26f in ???)
frame #15: 0x0 + 4641841936 (0x114ace310 in ???)
frame #16: 0x0 + 4641778194 (0x114abea12 in ???)
frame #17: 0x0 + 4641823470 (0x114ac9aee in ???)
frame #18: dlopen_internal(char const*, int, void*) + 185 (0x7fff203cfcb4 in libdyld.dylib)
frame #19: dlopen + 28 (0x7fff203be09e in libdyld.dylib)
frame #20: py_dl_open + 135 (0x107f33b97 in _ctypes.cpython-39-darwin.so)
<omitting python frames> zsh: abort      python3 -m openpifpaf.predict --help

any idea to fix this ? thank you.

**Comment by svenkreiss** [comment]
Can you please downgrade to pytorch 1.9.1 and torchvision 0.10.1 and then 
install with `pip3 install --no-build-isolation openpifpaf`?

PyTorch 1.10 has issues on MacOS and `--no-build-isolation` is generally necessary now.
