### ISSUE TITLE
'pip3 install openpifpaf' error

### ISSUE THREAD

**Issue by wangwei-630** [openpifpaf/openpifpaf#519]
Hi, I want to train this model on my machine(Ubuntu 16.04 torch1.9.0 Python 3.7), but there are many errors occurred when i run the command 'pip3 install openpifpaf'
```
Building wheels for collected packages: openpifpaf
Building wheel for openpifpaf (pyproject.toml) ... \  
.........  
[7/9] c++ -MMD -MF /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o.d -pthread -B /home/wangwei/anaconda3/envs/pifpaf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -I/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/TH -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/THC -I/home/wangwei/anaconda3/envs/pifpaf/include/python3.7m -c -c /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.cpp -o /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cpp -D_GLIBCXX_USE_CXX11_ABI=0
  FAILED: /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o
.......  
ERROR: Failed building wheel for openpifpaf  
Failed to build openpifpaf  
ERROR: Could not build wheels for openpifpaf, which is required to install pyproject.toml-based projects
```
Is there any steps I missed before running the command 'pip3 install openpifpaf'?

**Comment by svenkreiss** [comment]
I am slowly getting to the bottom of this. Please try with `pip3 install --no-build-isolation openpifpaf`.

**Comment by bewithme** [comment]
> Hi, I want to train this model on my machine(Ubuntu 16.04 torch1.9.0 Python 3.7), but there are many errors occurred when i run the command 'pip3 install openpifpaf'
> 
> ```
> Building wheels for collected packages: openpifpaf
> Building wheel for openpifpaf (pyproject.toml) ... \  
> .........  
> [7/9] c++ -MMD -MF /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o.d -pthread -B /home/wangwei/anaconda3/envs/pifpaf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -I/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/TH -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/THC -I/home/wangwei/anaconda3/envs/pifpaf/include/python3.7m -c -c /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.cpp -o /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cpp -D_GLIBCXX_USE_CXX11_ABI=0
>   FAILED: /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o
> .......  
> ERROR: Failed building wheel for openpifpaf  
> Failed to build openpifpaf  
> ERROR: Could not build wheels for openpifpaf, which is required to install pyproject.toml-based projects
> ```
> 
> Is there any steps I missed before running the command 'pip3 install openpifpaf'?

did you solve the problem?

**Comment by bewithme** [comment]
> I am slowly getting to the bottom of this. Please try with `pip3 install --no-build-isolation openpifpaf`.

it does't work

**Comment by wangwei-630** [comment]
> 
Yes, but I almost forgot the command I used cause i build this environment last year. You can try these command which i recorded.
1. pip3 install openpifpaf==0.12.14
2. pip3 install 'openpifpaf[train,test]'==0.12.14
3. pip3 install --editable '.[dev,train,test]'



> > Hi, I want to train this model on my machine(Ubuntu 16.04 torch1.9.0 Python 3.7), but there are many errors occurred when i run the command 'pip3 install openpifpaf'
> > ```
> > Building wheels for collected packages: openpifpaf
> > Building wheel for openpifpaf (pyproject.toml) ... \  
> > .........  
> > [7/9] c++ -MMD -MF /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o.d -pthread -B /home/wangwei/anaconda3/envs/pifpaf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -I/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/TH -I/tmp/pip-build-env-i2g5s631/overlay/lib/python3.7/site-packages/torch/include/THC -I/home/wangwei/anaconda3/envs/pifpaf/include/python3.7m -c -c /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.cpp -o /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_cpp -D_GLIBCXX_USE_CXX11_ABI=0
> >   FAILED: /tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/build/temp.linux-x86_64-3.7/tmp/pip-install-amjaahkb/openpifpaf_d58f8b9fbbd045b08d59136950e7b502/openpifpaf/csrc/src/cifdet.o
> > .......  
> > ERROR: Failed building wheel for openpifpaf  
> > Failed to build openpifpaf  
> > ERROR: Could not build wheels for openpifpaf, which is required to install pyproject.toml-based projects
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there any steps I missed before running the command 'pip3 install openpifpaf'?
> 
> did you solve the problem?

**Comment by Aakash007-ai** [comment]
i face the same problem
ERROR: Could not build wheels for openpifpaf, which is required to install pyproject.toml-based projects

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openpifpaf
Failed to build openpifpaf
ERROR: Could not build wheels for openpifpaf, which is required to install pyproject.toml-based projects

**Comment by kdoublerotor** [comment]
Same error here, but none of the aforementioned solutions fix the issue

**Comment by deepu-RW** [comment]
I installed Visual Build Tools and it worked
