### ISSUE TITLE
I can't use the api openpifpaf.show.Canvas.image(image)

### ISSUE THREAD

**Issue by Amoslzh** [openpifpaf/openpifpaf#524]
![image](https://user-images.githubusercontent.com/93984484/145703473-532168c9-0b21-4407-b295-b70e1d86f4dd.png)
when I use the with openpifpaf.show.Canvas.image(image) as ax: my kernel will crash
![image](https://user-images.githubusercontent.com/93984484/145703519-55711076-c2fb-43b2-82a2-2dda2c9a9ca3.png)
![image](https://user-images.githubusercontent.com/93984484/145703533-7e84cc11-1541-482b-a2d4-a10fb71fb6cb.png)

**Comment by Amoslzh** [comment]
The kernel is restarting. The kernel seems to hang up. It will restart automatically soon.

**Comment by svenkreiss** [comment]
This pattern is tested in the guide: https://openpifpaf.github.io/predict_api.html
Here is the corresponding Jupyter Notebook on GitHub: https://github.com/openpifpaf/openpifpaf/blob/main/guide/predict_api.ipynb

Does that help?
