### ISSUE TITLE
--checkpoint tshufflenetv2k16 could't run normally, but --checkpoint tshufflenetv2k30 is ok

### ISSUE THREAD

**Issue by zhangjiekui** [openpifpaf/openpifpaf#527]
my be tshufflenetv2k16 is trained on a pre  codebase. we can't load pretrained model file.

after modified torch/serialization.py:
   load_module_mapping: Dict[str, str] = {
        # See https://github.com/pytorch/pytorch/pull/51633
        'torch.tensor': 'torch._tensor',
        'openpifpaf_posetrack':  'openpifpaf',
        'openpifpaf_posetrack.backbone': 'openpifpaf.network.tracking_base',
        'openpifpaf_posetrack.heads': 'openpifpaf.network.tracking_heads',
        'openpifpaf_posetrack.heads.TBaseSingleImage': 'openpifpaf.network.tracking_heads.TBaseSingleImage',
        'openpifpaf_posetrack.headmeta': 'openpifpaf.headmeta',
    }

it can load and run , but the result is not as expected.

**Comment by svenkreiss** [comment]
It needed to be retrained for the new version of OpenPifPaf and we didnt have the resources.
