### ISSUE TITLE
--decoder-workers n (n>1) failed!

### ISSUE THREAD

**Issue by zhangjiekui** [openpifpaf/openpifpaf#528]
run: python -m openpifpaf.video  --decoder-workers 4 

RuntimeError: Tried to serialize object __torch__.torch.classes.openpifpaf_decoder_utils.Occupancy which does not have a __getstate__ method defined!

**Comment by svenkreiss** [comment]
I just tried it and it works now. I am adding a test for it in #543 to make sure this works on all future releases. Can you try again?
