### ISSUE TITLE
AttributeError: 'FFMpegWriter' object has no attribute '_proc'

### ISSUE THREAD

**Issue by uensal** [openpifpaf/openpifpaf#537]
Running the command:

> python -m openpifpaf.video --source=example.mp4 --video-output --json-output --checkpoint 'shufflenetv2k30-wholebody' --force-complete-pose

lead to the error: `AttributeError: 'FFMpegWriter' object has no attribute '_proc'` with an `ERROR: Unexpected segmentation fault encountered in worker.`

**Comment by wolfworld6** [comment]
> Running the command:
> 
> > python -m openpifpaf.video --source=example.mp4 --video-output --json-output --checkpoint 'shufflenetv2k30-wholebody' --force-complete-pose
> 
> lead to the error: `AttributeError: 'FFMpegWriter' object has no attribute '_proc'` with an `ERROR: Unexpected segmentation fault encountered in worker.`

hello,I meet this error,have you solved it ?

**Comment by uensal** [comment]
> > Running the command:
> > > python -m openpifpaf.video --source=example.mp4 --video-output --json-output --checkpoint 'shufflenetv2k30-wholebody' --force-complete-pose
> > 
> > 
> > lead to the error: `AttributeError: 'FFMpegWriter' object has no attribute '_proc'` with an `ERROR: Unexpected segmentation fault encountered in worker.`
> 
> hello,I meet this error,have you solved it ?

Unfortunately not. I started using another computer with python 3.10 and executed the following command that suddenly seemed to work. However I downloaded libraries and tried anything possible to make it work and I did it somehow.
`python3 -m openpifpaf.video --source=00_example.mp4 --video-output --json-output --checkpoint=shufflenetv2k30-wholebody --line-width=2 --force-complete-pose` 
My other computer still has the same error message. So unfortunately, I can not provide a solution there

**Comment by uensal** [comment]
> > > Running the command:
> > > > python -m openpifpaf.video --source=example.mp4 --video-output --json-output --checkpoint 'shufflenetv2k30-wholebody' --force-complete-pose
> > > 
> > > 
> > > lead to the error: `AttributeError: 'FFMpegWriter' object has no attribute '_proc'` with an `ERROR: Unexpected segmentation fault encountered in worker.`
> > 
> > 
> > hello,I meet this error,have you solved it ?
> 
> Unfortunately not. I started using another computer with python 3.10 and executed the following command that suddenly seemed to work. However I downloaded libraries and tried anything possible to make it work and I did it somehow. `python3 -m openpifpaf.video --source=00_example.mp4 --video-output --json-output --checkpoint=shufflenetv2k30-wholebody --line-width=2 --force-complete-pose` My other computer still has the same error message. So unfortunately, I can not provide a solution here

Dear @wolfworld6
I faced the issue again another computer.
What I did, was to upgrade to python version 3.8 and then calling `pip3 install opencv-python` and afterwards `pip3 install opencv-contrib-python` solved my problem. Hopefully that works on your side.
