### ISSUE TITLE
The new decoder cpp do not work with my Cif Caf field on custom subset keypoint

### ISSUE THREAD

**Issue by ledinhtri97** [openpifpaf/openpifpaf#539]
Hi. I have custom a model pose with 15 keypoints.
The decoder previously version python worked and now the newest repo have cpp decoder version and I want to try it.
Unfortunately the output of new cpp decoder version not work for my cif caf field.

I have a test script with file bin cif, caf field please help me investigate the problem.

you could get repo test from here: https://github.com/ledinhtri97/test_oppdecoder_cpp

change the code in the script to check result image. out.jpg
```
    # CIF field: [15, 5, 49, 85]
    # CAF field: [16, 9, 49, 85]
    cif_bin, cif, caf_bin, caf = get_custom_cifcaf()

    # CIF field: [17, 5, 151, 201
    # CAF field: [19, 8, 151, 201]
    # cif_bin, cif, caf_bin, caf = get_openpifpaf_cifcaf()

    cpp_decode(cif_bin, cif, caf_bin, caf)
```

![out](https://user-images.githubusercontent.com/16860306/158764621-ac437734-afcc-49df-869a-008984a1f5bd.jpg)

**Comment by svenkreiss** [comment]
If you are switching from 0.12 to 0.13, you might have to retrain. At least the head networks. Custom keypoints shouldn't be an issue.
Given we are not above version 1.0 yet, we use those version changes to signal breaking changes.
