### ISSUE TITLE
Custom dataset constants definitions

### ISSUE THREAD

**Issue by xenagarage** [openpifpaf/openpifpaf#547]
Hello, I want to contribute to OpenPifPaf by creating a plugin for lane estimation with my custom dataset. I did the annotation manually and exported the annotations as coco format. This is the first time I'm using coco format so I'm not sure if the annotation files are correct. They contain info, licenses, categories, images, and annotations but I couldn't manage to extract the keypoints and numeric valued constanst like skeleton from annotations json file. Should I extract them from that file, if so could you provide some information for how to do it, otherwise how can I define the constants?

[Here](https://github.com/senanursahin/openpifpaf-dev/tree/main/src/openpifpaf/plugins/lane) is my plugin code and [train annotation json file](https://github.com/senanursahin/openpifpaf-dev/blob/main/src/openpifpaf/plugins/lane/data-lane/annotations/lane_keypoints_train.json). I followed your guides and as the last step before training I need to provide the constants. As I see in apollo3d, wholebody, animalpose etc plugins, keypoints are provided already in dataset and defined in documentations. Since in my case I don't have it and it's my own custom dataset, my question is how can I define or where can I find the constant values, can I define the keypoint strings like 'corner_1' etc or should I extract it from somewhere?

Thanks in advance!

**Comment by clearliu777** [comment]
hi, are you solved the training problems

**Comment by xenagarage** [comment]
hi @clearliu777 unfortunately I haven't

**Comment by xenagarage** [comment]
hi @clearliu777 unfortunately I haven't
