### ISSUE TITLE
NumPy: No module named 'numpy' (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:68.)   python 3.10, ubuntu 18

### ISSUE THREAD

**Issue by venkatshivap** [openpifpaf/openpifpaf#548]
Hi I'm getting below error. I tried long time solving it but no luck. Could you please help me ASAP.

**I'm trying out below command  for import error
pip3 install -e .**

 Running setup.py develop for openpifpaf
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [10 lines of output]
        /tmp/pip-build-env-hdkjpnwa/overlay/local/lib/python3.10/dist-packages/torch/_masked/__init__.py:223: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:68.)
          example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
        /usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
          warnings.warn(msg)
        usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: setup.py --help [cmd1 cmd2 ...]
           or: setup.py --help-commands
           or: setup.py cmd --help
        
        error: option --user not recognized
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in /home/ubuntu/.local/lib/python3.10/site-packages
  Rolling back uninstall of openpifpaf
  Moving to /home/ubuntu/.local/lib/python3.10/site-packages/openpifpaf-0.13.3.dist-info/
   from /home/ubuntu/.local/lib/python3.10/site-packages/~penpifpaf-0.13.3.dist-info
  Moving to /home/ubuntu/.local/lib/python3.10/site-packages/openpifpaf/
   from /home/ubuntu/.local/lib/python3.10/site-packages/~penpifpaf
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [10 lines of output]
    /tmp/pip-build-env-hdkjpnwa/overlay/local/lib/python3.10/dist-packages/torch/_masked/__init__.py:223: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:68.)
      example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
    /usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --user not recognized
    [end of output]

**Comment by svenkreiss** [comment]
It seems distutils is very old in your installation. Can you run `pip3 install --upgrade pip setuptools` which I believe will also update distutils?
