### ISSUE TITLE
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

### ISSUE THREAD

**Issue by xenagarage** [openpifpaf/openpifpaf#549]
Hi,

I'm trying to train a Lane Detection plugin. For that I annotated Apollo Lane Detection dataset on polynomial lane keypoints and prepared the beloved COCO json files. Also prepared a lane_kp.py file for specifics just from following how other plugins are trained by OpenPifPaf.

When I first tried to train with a very little dataset, the model didn't even annotated the lanes, didn't learned.
So I added more pictures but right now my problem is that on my system ((Ubuntu 20.04, Memory 31.1 GiB, Processor 11th Gen Intel® Core™ i7-11800H @ 2.30GHz × 16 , GPU NVIDIA RTX 3080, Disk 1.0 TB) I'm getting **Process finished with exit code 137 (interrupted by signal 9: SIGKILL)** error on very first steps of training. I tried clearing cache, restarting PyCharm IDE, clearing PyCharm's cache and also restarting my computer.
Unfortunately nothing helped.
The full output is shown below. Any suggestion means the world for me, please leave any comment that occurs so that I can test since I tested everything that came to my mind or Google forums suggested.
Also what's going on with my system memory could be found on the attached image.
![Screenshot from 2022-05-10 18-08-08](https://user-images.githubusercontent.com/48882047/167664107-827bea41-e1ac-48bb-9366-4d7b4d9fca08.png)

creating index...
index created!
INFO:openpifpaf.plugins.coco.dataset:Images: 100
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
INFO:openpifpaf.plugins.coco.dataset:Images: 30
INFO:openpifpaf.optimize:SGD optimizer
INFO:openpifpaf.optimize:training batches per epoch = 10
INFO:openpifpaf.network.trainer:{'type': 'config', 'field_names': ['lane.cif.c', 'lane.cif.vec', 'lane.cif.scales', 'lane.caf.c', 'lane.caf.vec', 'lane.caf.scales']}
INFO:openpifpaf.network.trainer:model written: outputs/bizimki_shufflenetv2k16-220510-181400-lane.pkl.epoch000
INFO:openpifpaf.network.trainer:{'type': 'train', 'epoch': 0, 'batch': 0, 'n_batches': 10, 'time': 21.934, 'data_time': 34.002, 'lr': 1e-07, 'loss': 860.493, 'head_losses': [91.748, 306.094, 1.814, 141.696, 317.115, 2.025]}
INFO:openpifpaf.network.trainer:applying ema
INFO:openpifpaf.network.trainer:{'type': 'train-epoch', 'epoch': 1, 'loss': 527.42487, 'head_losses': [37.01228, 207.03117, 1.44643, 66.77843, 213.64878, 1.50778], 'time': 158.7, 'n_clipped_grad': 0, 'max_norm': 0.0}
INFO:openpifpaf.network.trainer:restoring params from before ema
INFO:openpifpaf.network.trainer:{'type': 'train', 'epoch': 1, 'batch': 0, 'n_batches': 10, 'time': 16.056, 'data_time': 30.782, 'lr': 0.0001, 'loss': 355.21, 'head_losses': [-74.29, 249.839, 1.339, -38.662, 215.438, 1.545]}
INFO:openpifpaf.network.trainer:applying ema
INFO:openpifpaf.network.trainer:{'type': 'train-epoch', 'epoch': 2, 'loss': 420.5383, 'head_losses': [-51.05916, 266.32344, 1.30207, -26.86795, 229.48822, 1.35168], 'time': 150.4, 'n_clipped_grad': 0, 'max_norm': 0.0}
INFO:openpifpaf.network.trainer:restoring params from before ema
INFO:openpifpaf.network.trainer:{'type': 'train', 'epoch': 2, 'batch': 0, 'n_batches': 10, 'time': 15.14, 'data_time': 39.271, 'lr': 0.0001, 'loss': 716.852, 'head_losses': [-25.397, 371.435, 1.585, -14.655, 382.17, 1.714]}

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

**Comment by svenkreiss** [comment]
Seems like out of memory and out of swap space. The system is protecting itself by sending an aggressive SIGKILL to terminate the process.

**Comment by xenagarage** [comment]
Thanks for your answer @svenkreiss , I only tried to train with 130 pictures 10 epoch and 30 GiB memory not being enough is looking like a logic error, is the network of Openpifpaf really this harsh? If so I would swipe to Colab.
But regardless of this SIGKILL issue I feel like I have mistakes on my input approaches.
Is there any chance I could see one of your annotation json files?

I would like to revise my annotations regarding to your keypoint COCO format and there's a huge lack of information on the internet when it comes to COCO keypoint format and keypoint annotators. May I ask which annotation tool have the team used?

That would be great if I could follow your input format sample since there's no json file on the repository. Thanks in advance.

**Comment by svenkreiss** [comment]
I have no more information than what is on the COCO website:
* https://cocodataset.org/#format-data
* https://cocodataset.org/#download contains a link to the train/val annotations
