### ISSUE TITLE
Can Tracking detections be improved to match the Non-Tracked detections? (Best of both worlds)

### ISSUE THREAD

**Issue by njho** [openpifpaf/openpifpaf#553]
I see [github.com/openpifpaf_posetrack](https://github.com/openpifpaf/openpifpaf_posetrack) has been migrated here so posting the question here.

After following `openpifpaf_posetrack` instructions and installing with `openPifPaf==0.12.5` (`pip install openpifpaf==0.12.5`) in order to get it working I noticed that the detections from **non-tracked** and **tracked** differ quite a bit.

### Questions
1. Is there a setting with the tracking args that can be used in order to have tracking detections match non-tracked?
2. Would a new decoder need to be trained?

If it's possible, and it's a matter of wiring up code to achieve this, I'd happy to do a PR so long as I'm pointed in the right direction. I'm also not an ML superstar and wouldn't be able to train models however.

### **Non-Tracked on openPifPaf== 0.12.5**
`python3 -m openpifpaf.video --source source.mp4 --video-output --json-output`
![image](https://user-images.githubusercontent.com/16584869/170777184-e0fe0e13-cd9b-4be9-b98d-9f1bc285a472.png)

### **Tracking using openPifPaf==0.12.5**
`MPLBACKEND=macosx python3 -m openpifpaf.video --show --long-edge=321 --checkpoint=tshufflenetv2k16 --decoder=trackingpose:0 --source source.mp4 --video-output --json-output`
![image](https://user-images.githubusercontent.com/16584869/170774317-06b78d07-100e-414a-8b15-b6466660515d.png)

**Comment by svenkreiss** [comment]
You can try tracking with single image models. This was a baseline for our paper: `MPLBACKEND=macosx python3 -m openpifpaf.video --show --long-edge=321 --checkpoint=shufflenetv2k16 --decoder=posesimilarity:0 --source 0 --horizontal-flip`

**Comment by svenkreiss** [comment]
I am adding some clarifications into #554

**Comment by njho** [comment]
Thanks for the clarifications!

I ended up running a bunch of different variations just to see how they performed differently and also because I didn't really understand which combinations matched with which.

The outputs from variations video can be found here: https://drive.google.com/file/d/16OkEMNGUu_2Q8ViddbL3Ga0phn64tKfM/view?usp=sharing

Generally found that the `tshufflenetv2k16` with `trackingpose` looked best. Followed by `tshufflenetv2k30` w/ `trackingpose`.

Root command: `python -m openpifpaf.video --long-edge=321 --source /tmp/small-clip-cardi_frame.mp4 --video-fps 24 --video-output --json-output`

**OpenPifPaf==0.12.5 & openpifpaf_posetrack**
`--checkpoint=tshufflenetv2k16 --decoder=trackingpose:0`
`--checkpoint=tshufflenetv2k16 --keypoint-threshold 0.05 --decoder=trackingpose:0`
`--checkpoint=tshufflenetv2k16 --decoder=posesimilarity:0` 

No support for `tshufflentvk30`

**OpenPifPaf==0.13.3**
`--checkpoint=tshufflenetv2k30 --decoder=trackingpose:0`
`--checkpoint=tshufflenetv2k30  --decoder=trackingpose:0 --keypoint-threshold 0.05`
`--checkpoint=tshufflenetv2k30  --decoder=trackingpose:0 --tr-single-pose-threshold 0.1 --tr-multi-pose-threshold 0.1`
`--checkpoint=tshufflenetv2k30 --decoder=posesimilarity:0`
`--checkpoint=tshufflenetv2k30 --decoder=posesimilarity:0 --keypoint-threshold 0.05 `
`--checkpoint=shufflenetv2k16 --decoder=posesimilarity:0`
`--checkpoint=shufflenetv2k16 --decoder=posesimilarity:0  --keypoint-threshold 0.05 `
`--checkpoint=shufflenetv2k30 --decoder=posesimilarity:0`
`--checkpoint=shufflenetv2k30 --decoder=posesimilarity:0  --keypoint-threshold 0.05 `

No support
`--checkpoint=tshufflenetv2k16 --decoder=trackingpose:0`
`--checkpoint=shufflenetv2k16 --decoder=trackingpose:0`
`--checkpoint=shufflenetv2k16 --decoder=trackingpose:0 --keypoint-threshold 0.05`
`--checkpoint=tshufflenetv2k16 --keypoint-threshold 0.05 --decoder=trackingpose:0`
`--checkpoint=tshufflenetv2k16 --decoder=posesimilarity:0`
`--checkpoint=tshufflenetv2k16 --keypoint-threshold 0.05 --decoder=posesimilarity:0`
`--checkpoint=shufflenetv2k30 --decoder=trackingpose:0`
`--checkpoint=shufflenetv2k30 --decoder=trackingpose:0 --keypoint-threshold 0.05`
