### ISSUE TITLE
Cannot Find Model tshufflenetv2k16

### ISSUE THREAD

**Issue by tingyihello** [openpifpaf/openpifpaf#559]
I use openpifpaf==0.12.14. I can not find the model tshufflenetv2k16 for tracking.
`>>> import openpifpaf
>>> list(openpifpaf.BASE_FACTORIES.keys())
['mobilenetv2', 'mobilenetv3large', 'mobilenetv3small', 'resnet18', 'resnet50', 'resnet101', 'resnet152', 'resnext50', 'resnext101', 'shufflenetv2x1', 'shufflenetv2x2', 'shufflenetv2k16', 'shufflenetv2k20', 'shufflenetv2kx5', 'shufflenetv2k30', 'shufflenetv2k44', 'squeezenet', 'swin_t', 'swin_s', 'swin_b', 'swin_b_window_12', 'swin_l', 'swin_l_window_12', 'xcit_nano_12_p16', 'xcit_tiny_12_p16', 'xcit_tiny_24_p16', 'xcit_small_12_p16', 'xcit_small_24_p16', 'xcit_medium_24_p16', 'xcit_large_24_p16', 'xcit_nano_12_p8', 'xcit_tiny_12_p8', 'xcit_tiny_24_p8', 'xcit_small_12_p8', 'xcit_small_24_p8', 'xcit_medium_24_p8', 'xcit_large_24_p8', 'effnetv2_s', 'effnetv2_m', 'effnetv2_l', 'effnetv2_xl', 'effnetv2_s16_s', 'effnetv2_s16_m', 'effnetv2_s16_l', 'effnetv2_s16_xl', 'botnet', 'cifar10net']`

**Comment by svenkreiss** [comment]
This is the output for 0.13.4:

```
  --checkpoint CHECKPOINT
                        Path to a local checkpoint. Or provide one of the following to download a pretrained model: ['shufflenetv2k30-animalpose', 'shufflenetv2k16-apollo-24', 'shufflenetv2k16-apollo-66',
                        'shufflenetv2k30-apollo-66', 'mobilenetv2', 'mobilenetv3small', 'mobilenetv3large', 'resnet50', 'shufflenetv2k16', 'shufflenetv2k16-withdense', 'shufflenetv2k30', 'swin_s', 'swin_b',
                        'swin_t_input_upsample', 'mobilenetv3small-cocodet', 'resnet18-cocodet', 'resnet50-crowdpose', 'shufflenetv2k16-nuscenes', 'tshufflenetv2k30', 'shufflenetv2k16-wholebody',
                        'shufflenetv2k30-wholebody'] (default: None)
  --basenet BASENET     base network, one of ['mobilenetv2', 'mobilenetv3large', 'mobilenetv3small', 'resnet18', 'resnet50', 'resnet101', 'resnet152', 'resnext50', 'resnext101', 'shufflenetv2x1',
                        'shufflenetv2x2', 'shufflenetv2k16', 'shufflenetv2k20', 'shufflenetv2kx5', 'shufflenetv2k30', 'shufflenetv2k44', 'squeezenet', 'swin_t', 'swin_s', 'swin_b', 'swin_b_window_12',
                        'swin_l', 'swin_l_window_12', 'xcit_nano_12_p16', 'xcit_tiny_12_p16', 'xcit_tiny_24_p16', 'xcit_small_12_p16', 'xcit_small_24_p16', 'xcit_medium_24_p16', 'xcit_large_24_p16',
                        'xcit_nano_12_p8', 'xcit_tiny_12_p8', 'xcit_tiny_24_p8', 'xcit_small_12_p8', 'xcit_small_24_p8', 'xcit_medium_24_p8', 'xcit_large_24_p8', 'effnetv2_s', 'effnetv2_m', 'effnetv2_l',
                        'effnetv2_xl', 'effnetv2_s16_s', 'effnetv2_s16_m', 'effnetv2_s16_l', 'effnetv2_s16_xl', 'botnet', 'tshufflenetv2k16', 'tshufflenetv2k30', 'tresnet50', 'cifar10net'] (default: None)
```

There is a pretrained tshufflenetv2k30 and basenetworks defined for tshufflenetv2k16 and tshufflenetv2k30.
