### ISSUE TITLE
Incorrect filtering of GT annotations in toannotations.py

### ISSUE THREAD

**Issue by krishnakanthnakka** [openpifpaf/openpifpaf#576]
I think the GT annotations are filtered incorrectly in the ```src/transforms/toannotations.py``` file

https://github.com/openpifpaf/openpifpaf/blob/f797feebaad375b10b3f6db8fd8656fd6ea9c4ca/src/openpifpaf/transforms/toannotations.py#L44

```ann['keypoints']``` is an  2-D array of shape ```(J, 3)``` instead of ```(Jx3, )```. So the condition: ```ann['keypoints'][2::3]>0.0``` checks every 3rd row to create annotation object.  

Changing to ```ann['keypoints'][:, 2]>0.0``` works fine. 

That said, this issue  does not seem to have any effect on the computed COCO metrics as the GT annotations are loaded in the COCO library prior to this filtering at 
https://github.com/openpifpaf/openpifpaf/blob/f797feebaad375b10b3f6db8fd8656fd6ea9c4ca/src/openpifpaf/plugins/coco/cocokp.py#L326 

Can you please check and correct me if I'm wrong?

**Comment by svenkreiss** [comment]
Yes, your analysis seems correct. Do you want to open a pull request with the change?

**Comment by krishnakanthnakka** [comment]
Yes, I will do it soon. 
Thank you for your quick response.
