### ISSUE TITLE
openpifpaf/_cpp.so: undefined symbol: _ZN2at4

### ISSUE THREAD

**Issue by Darius-H** [openpifpaf/openpifpaf#605]
I got the following problem:
```
Traceback (most recent call last):
  File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/bn/ailabrenyi/entries/huangjiawei/Avatar/PyMAF-X/apps/demo_smplx.py", line 56, in <module>
    from openpifpaf import decoder as ppdecoder
  File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
    cpp_extension.register_ops()
  File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 27, in register_ops
    torch.ops.load_library(ext_specs.origin)
  File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /mnt/bn/ailabrenyi/entries/huangjiawei/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
```
My openpifpaf version is :openpifpaf-0.13.11
My torch environment is:
```
pytorch-lightning              1.5.7
pytorch3d                      0.7.4
torch                          1.12.1
torchaudio                     0.12.1
torchvision                    0.13.1
```
and the linux environment is:
```
Debian GNU/Linux 10 (buster)
```

**Comment by lyk412** [comment]
> I got the following problem:
> 
> ```
> Traceback (most recent call last):
>   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/mnt/bn/ailabrenyi/entries/huangjiawei/Avatar/PyMAF-X/apps/demo_smplx.py", line 56, in <module>
>     from openpifpaf import decoder as ppdecoder
>   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
>     cpp_extension.register_ops()
>   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 27, in register_ops
>     torch.ops.load_library(ext_specs.origin)
>   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
>     ctypes.CDLL(path)
>   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/ctypes/__init__.py", line 382, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /mnt/bn/ailabrenyi/entries/huangjiawei/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
> ```
> 
> My openpifpaf version is :openpifpaf-0.13.11 My torch environment is:
> 
> ```
> pytorch-lightning              1.5.7
> pytorch3d                      0.7.4
> torch                          1.12.1
> torchaudio                     0.12.1
> torchvision                    0.13.1
> ```
> 
> and the linux environment is:
> 
> ```
> Debian GNU/Linux 10 (buster)
> ```

Hi, I met the same problem.  Do you fix it now?

**Comment by Darius-H** [comment]
> > I got the following problem:
> > ```
> > Traceback (most recent call last):
> >   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/mnt/bn/ailabrenyi/entries/huangjiawei/Avatar/PyMAF-X/apps/demo_smplx.py", line 56, in <module>
> >     from openpifpaf import decoder as ppdecoder
> >   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/__init__.py", line 11, in <module>
> >     cpp_extension.register_ops()
> >   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/cpp_extension.py", line 27, in register_ops
> >     torch.ops.load_library(ext_specs.origin)
> >   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
> >     ctypes.CDLL(path)
> >   File "/home/tiger/nfs/Avatar/miniconda3/envs/v2a/lib/python3.9/ctypes/__init__.py", line 382, in __init__
> >     self._handle = _dlopen(self._name, mode)
> > OSError: /mnt/bn/ailabrenyi/entries/huangjiawei/Avatar/miniconda3/envs/v2a/lib/python3.9/site-packages/openpifpaf/_cpp.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My openpifpaf version is :openpifpaf-0.13.11 My torch environment is:
> > ```
> > pytorch-lightning              1.5.7
> > pytorch3d                      0.7.4
> > torch                          1.12.1
> > torchaudio                     0.12.1
> > torchvision                    0.13.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the linux environment is:
> > ```
> > Debian GNU/Linux 10 (buster)
> > ```
> 
> Hi, I met the same problem. Do you fix it now?

I find that in their release: https://github.com/openpifpaf/openpifpaf/releases. Each openpifpaf version corresponds to a specific pytorchversion, and we may have trouble when not using that specific version. I finally use openpifpaf==0.13.1 and pytorch==1.9.0 and it works well.
They should emphasize this version matching problem in Readme.md.
